### ISSUE TITLE
Create a list of patterns and practices

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#12]
This should be done in https://github.com/Polyjuice/Polyjuice/wiki

Can be moved elsewhere in future

Questions to answer:
- what is the project structure
- is there a `src` directory
- where is `bower.json`
- conventions for file naming
- what is the path to static assets
- URL and Ontology mapping conventions
- standalone app conventions
- etc

**Comment by warpech** [comment]
Naming conventions should be explained similarly to 
- http://guides.emberjs.com/v1.10.0/concepts/naming-conventions/

**Comment by miyconst** [comment]
@warpech here is a wiki page which covers some of the points:
https://github.com/Polyjuice/Polyjuice/wiki/Polyjuice-project-structure

**Comment by miyconst** [comment]
@warpech, @andwah, @tomalec I have updated the wiki page according to the new project structure.

Please verify that everything is right and I will put in order my projects.

**Comment by dan31** [comment]
More patterns and practices! :+1:

**Comment by warpech** [comment]
Great diagram! Is it hand made?

I made some minor edits:
- the introduction is now more compact
- clarified about VS files

Please go on with adapting the projects.

**Comment by miyconst** [comment]
Yes, it is hand made :)

The only one folder we missed out is the content folder. In People app I have `default-layout.sql` file. Which is not a part of wwwroot but also not a part of server side code. We need a folder for such files.

**Comment by miyconst** [comment]
Another folder we forget about is `dist` which contains `.zip` packages for app store.

**Comment by warpech** [comment]
I am not familiar with how such folder is normally called, but I am fine with `content` if you propose so.

`dist` is now `packages` (such folder is created by VS "Publish" feature)

**Comment by warpech** [comment]
As discussed on Skype, the Project Structure needs the following changes:

- describe the usage of namespaces:
 - use shallow namespace (`namespace UserAdmin {`)
- use PascalCase for folders that contain CS code
- add StandalonePage.html to the diagram

**Comment by miyconst** [comment]
Updated wiki page.

**Comment by dan31** [comment]
We discussed the project structure late evening yesterday with Konstantin.

Below are our takeaways:

1) __All facilities for app standalonization would go away for inheritance from some base-class library__ (to not write those redundant pieces of if-s every time). As well, we may __add default Standalone.html and LauncherWrapper.html__ files. If the developer wants, he might change page.Html to something else, if not then just use the default file.

2) __All dependencies would go away from repo and will be dynamically fetched to /sys__ (like is vNext nuget deps).

3) __Bat files are to be deleted from repos and moved__ to a platform (some shared place, even StarcounterBin). They shouldn't be in-repo, and there are no bat files on osx and linux (that is a control question).

4) __The “pill rule” would apply__: "If you are sick – follow instructions of the pill strictly, if not sick – don’t consume the pill at all".

Let’s say, when you code, you always create { } even for a single-line statement on conditionals. That’s good practice, it prevents logical errors. If you have one file js, one css, one html, just put them together in Client / wwwroot (whatever you call that place) without folders js, css, html. Perhaps, if in total they are more that 10 files, consider making your folders. You will prevent no error, if you will enforce every team member put js in js, css in css always. So, simple "one line" app could contain all of the client files inside a folder. There still should be a strong naming for js, css, html folder, once they are decided for using. So:

6) Should be strict naming conventions, but within the “pill rule”.

7) Should be dedicated locations for “Tests” and “Client”. "wwwroot" might be obligatory naming, if going for nuget-way. But "Client" name is more case-consistent and we got quite used to it.

8) Flatter structure, less nesting (inspired by vNext as well). 1 level of nesting in most cases is preferable. Just have code files near sln, if you have few of them.

9) While writing json-files, we should be consistent towards using quotes in names:

> Once I tried to feed NodeJs with such json, and it gave me a very nice exception: "Your packages.json files is incorrect, tell the app developer to fix it. Json files should be in json format, not just JavaScript".

As well, Visual Studio json editor starting from 2013 insists on that, highlighting omitted quotes with green line. So it makes sense to always format it with quotes.

WDYT @warpech, @miyconst, @andwah?

**Comment by miyconst** [comment]
The only one point which worries me is 2)

It is good to fetch dependencies with bower, but lets say the dependency was changed and the change broke an app, in this case we don't have a working copy of app and have to fix the app or the dependency.

**Comment by warpech** [comment]
Hi! Good findings!

1) Totally agree about `StandalonePage.html`. Regarding `LauncherWrapperPage.html`, @tomalec is making efforts to get rid of it completely.

2) Can you elaborate on the good sides of it? I see 3 major problems and not a single benefit:
- if lib files are not checked in to VCS, the build script needs to check if locally installed libs are in the same version as defined in JSON file and update files if needed. This needs to be added to the build script, and develeper needs to remember about updating dependencies locally (because he may have libs in old versions).
- `bower.json`/`project.json` must include exact version number to receive the same lib version that was tested. Currently we can afford loose version numbering for dependencies because they are updated with bower only when needed (not with each build).
- external resource is needed to build the project (what happens when I'm on a plane, or Bower/NPM/NuGet registry is down?)

3) It is true that currently most of the bat files do the same. On the other hand, I have seen many cross-platform projects that make available both `.bat` and `.sh` scripts, that execute on all platforms. What do you propose as a substitute? Can you prepare sample platform-wise scripts to build/package/run projects?

4) Totally agree.

6) Any examples about how the "pill rule" applies to file naming?

7) In vNext, does the Test directory belong to the project or outside the project? `wwwroot` is actually configurable via `webroot` property in `project.json` and just happens to be the default.

8) How does it look in vNext? I am sure they don't use `sln` and `csproj`, but `global.json` and `project.json`. Should we use `sln`/`global.json` at all, or just stick to `csproj`/`project.json`?

9) Totally agree. @Starcounter-Jack likes to emphasise that our JSON parser is forgiving, but it may look annoying to someone and fail to work with other tools.

**Comment by dan31** [comment]
> 2) Can you elaborate on the good sides of it? I see 3 major problems and not a single benefit:

Sadly I'm not knowledgable on practices from web dev, for me checked-in dependencies feel like committing binary files or library sources to repo. The main reason contra is that you aren't going to change and version those files yourself. In old-school version control system one could use ```svn:external``` to check-out needed dependencies from original dependencies repos when you check-out your repo. If you need to build ```boost``` from sources, you don't commit ```boost``` to your repo, but let your repo check it out from ```boost``` repo.

Today you use package managers, ```nuget``` is a bright example, much better alternative. If you need ```boost``` in compiled form, then you can take them as a nuget-dependency (you restore nuget-dependency when project is loaded). If you need a customized build of ```boost```, you can run your local nuget-server and distribute the dependency.

The cooler example is new .NET. To run your .NET exe, before you had to install .NET Framework of the needed version. Now you can ship that exe, and the runtime will restore all needed parts of Framework for you automatically. So you require a dependency as a config of your app, not carry dependency around with the app. I believe this is the best approach today, because it has been proven on practice and evolutional.

> if lib files are not checked in to VCS, the build script needs to check if locally installed libs are in the same version as defined in JSON file and update files if needed. This needs to be added to the build script, and develeper needs to remember about updating dependencies locally (because he may have libs in old versions).

I think the right question here would be "when the dependencies should be resolved". On one hand, you have an app source and build it in your environment (VS, or node, or go, or ...). Then the dependencies should be resolved by the build environment. However, 1) we now talk of client-side deps, AND 2) apps can be uploaded in compiled form. Those 2 points lead us to an idea: what if client-side dependencies are resolved by the platform, somewhen right after the app is launched in Starcounter? Or even when apps are "installed" to Starcounter, all those dependencies will be added to /sys by Starcounter __somehow__. Not discussing how exactly, WDYT on the idea? Smart fetching of client-side deps can be a nice feature of platform. We can think of it like that: Starcounter recognize the dependency and makes it local (putting to /sys). Starcounter might simply invoke commonly used package managers like bower, but __at a right moment__.

> bower.json/project.json must include exact version number to receive the same lib version that was tested. Currently we can afford loose version numbering for dependencies because they are updated with bower only when needed (not with each build).

Shouldn't we encourage explicit stating of dependency version? All thick client-side sources I've seen so far require specific version of the library (bootstrap, jquery etc). Being less explicit with libraries version (saying I need latest "3.x" but not "3.1.4") can lead to unexpected degradation of user experience. Correct me if I'm wrong. If a developer prefers to specify only a major number of the version, we can afford that, but then Starcounter should push a version update at right moment. As I guessed above, idea is to let Starcounter invoke that at a right moment. Practically that would mean to implement that from https://github.com/Polyjuice/Barcodes2/issues/3 – how to ```connect to Bower and/or NPM for <script/> and <link/> references```?

> external resource is needed to build the project (what happens when I'm on a plane, or Bower/NPM/NuGet registry is down?)

If the dependency you need is not in /sys yet, developer is doomed. I won't be doomed because I like to fly as well :) But we can prefetch popular dependencies into /sys beforehand, when Starcounter is being installed to a machine.

> 3) It is true that currently most of the bat files do the same. On the other hand, I have seen many cross-platform projects that make available both .bat and .sh scripts, that execute on all platforms. What do you propose as a substitute? Can you prepare sample platform-wise scripts to build/package/run projects?

When @parherman will be available for that, we'll definitely propose. The thing is that we have to build those apps explicitly. In future it should be as easy as to upload your code to a cloud and app will run. It means that the platform would build the code for you. As well, ```bat``` and ```sh``` in cross-platform libraries normally should be light-weight tooling around the build system. Say, you want to produce Visual Studio projects on Windows, but makefiles on Linux, for that you have a ```bat``` and ```sh``` and trigger them, but inside they just download and trigger cmake. For the same reason, we want to move from ```bat``` to Python or something equally lightweight to write tests, ```bat``` isn't a good tool to write logic, it should be more like a macrotool, to save time for you not entering multiple command-line calls every time.

> 6) Any examples about how the "pill rule" applies to file naming?

Jocke also refers to a toilet rule there :) I think the pill rule is important for us as a team. If another team wants to use thatCase not ThisCase, why not? But if they want some guides, we can recommend our guide, which we use on our own. E.g., if you want to structure your wwwroot internally, you will use ```js``` and ```css``` folders, but not ```JS``` and ```CsS``` folders, because other members of your team do equally and you want to be consistent over the team members. We don't force other teams outside Starcounter do so (ISVs), because this changes nothing, but if they need a choice ("Guys, how do you name?"), we can suggest our way. Frequently people look for some good defaults to start with. For us as a team good defaults will encourage everyone issue pull requests to code of other team members more freely, since everyone will follow the same codeguide, no tab wars in repos etc (I saw how it happens, we must avoid that).

> 7) In vNext, does the Test directory belong to the project or outside the project?

Not sure if there is any requirement at all. Tests are specified differently (like a test class and alike). I think ```src``` and ```test``` is a good location, I met such in many libraries. We discussed with Konstantin as well whether we need to have ```src``` and ```test``` or we can go flatter, but now I don't really see a need to make it flatter and put a ```Test``` folder into a ```src``` with putting the contents of ```src``` upper.

> wwwroot is actually configurable via webroot property in project.json and just happens to be the default.

Do we find ```wwwroot``` a good default choice? I believe it's consistent with nuget, but is it consistent with us? Before we used ```Client``` and were happy, or not really?

> 8) How does it look in vNext? I am sure they don't use sln and csproj, but global.json and project.json. Should we use sln/global.json at all, or just stick to csproj/project.json?

Such files now just reside flat together with sources, no special folder proposed by default, if that is what you mean.

**Comment by Starcounter-Jack** [comment]
```wwwroot``` is just the default. Read the project.json specs. 

Regarding how "they" do it in 2013. 

We should be looking into the future, not the past. What would 2025 be like? Not how did they do it in 2013. Looking at 2013 essentially means, how did they design it back in 2009 (as they are usually design long before you ship and they are always behind the times). We are not application developers or technology consumers, we are creators of the next generation. 

Remember, the upcoming live coding event in San Fransisco. We should be creating stuff live. Think big and different.

1. No compilation cycle and no roundtrip time
2. Minimal typing
3. Immediate overview and comprehension for beginners
4. Every keystroke and line of code should provide one of these three virtues:  
   a) Looks of the application
   b) Application behaviour
   c) Mapping 

Point 4 means that we should avoid boilerplate and overhead to the extreme.

**Comment by Starcounter-Jack** [comment]
There is no longer any ```.sln``` or ```.csproj```. This is legacy and we keep it as temporary artefacts only as long as we need to.

**Comment by Starcounter-Jack** [comment]
When you browser the web for a open source app you want to dig in to, you are put of by 100 files in ```/src``` and 3 files in ```/test```, but if the app only consists of 3 files in ```/src```, you are happy even if there are a 100 files in ```/test```. Remember that our primary goal is to make things easy to comprehend and dig in to.

People already know how to add more folders. No one is going to create ten thousand source code files without their own well thought out subfolder. They will have very good reason to create the grouping that makes sense to **their** domain and project. Our job is to make in uber clean and uber simple.


Because these are server side apps, we keep the test as an integral part of the app.

**Comment by Starcounter-Jack** [comment]
The ```wwwroot``` should be flat if there are three files. When you have hundreds of .css files, one subfolder is to few and when you have a single one, ten subfolders are too many.

**Comment by Starcounter-Jack** [comment]
Any comments on the Lilliput egg wars?

**Comment by Starcounter-Jack** [comment]
How can we make Barcode2 simpler, smaller and easier to grok?

**Comment by Starcounter-Jack** [comment]
The advantage of ```/src```, ```/tests``` and ```/wwwroot``` is that most people would probably be able to guess what is inside them without training or reading the documentation.

**Comment by Starcounter-Jack** [comment]
```.bat``` files are banned as they do not work cross platform.

**Comment by Starcounter-Jack** [comment]
The package managed paths are important as we will need to be able to fiddle new applications with the customer sitting across the table. We could cache the packages on the database server as well as on www.starcounter.com to secure availability. I.e. if the original host is unavailable, we still serve the bits.

1. The browsers asks for /sys/bower/foo/1.x
2. The starcounter server gets the bits from bower.starcounter.com
3. ```bower.starcounter.com``` gets the bits from the original host
4. The files are only downloaded once and the files are kept

The above is optional. You can use any other method if you feel it is better. We need this to be able to develop stuff in the live jamming session.

As a reminder. The live jamming session is this:

1. Ask the customer across the table what he wants to see built.
2. Open a playground by visiting www.polyjuice.com
3. Bring down a dozen or so existing apps
4. Click the fiddle app and write some code for the missing stuff (for instance the barcode app)
5. Watch the customer being amazed

**Comment by Starcounter-Jack** [comment]
Mapping code cannot be a part of the compiled bits.

1. The map is just the default map. 
2. The map needs to be editable at runtime
3. The map needs to be in source code format as it will be used as a security layer. The database will only be readable and writeable in the aspects that are mapped in future versions of Starcounter. If the table is not mapped, it is not readable or writeable. This enables the customer to discover if the People app will be able to update product prices. This is similar to entitlements on other sandboxed platforms.

So when you install an app, you will get a default mapping alongside it.

**Comment by Starcounter-Jack** [comment]
I strongly believe that vendors should have standards (big or small letters? hyphens or camel case? curly-brace on new line, etc.)

However, getting opinionated on this is the way of the 90s. For this, let other people do the fighting. Please read up on the Lilliput egg wars.

**Comment by dan31** [comment]
@warpech, what are the plans for restructuring apps code for no-glue simple structure?

**Comment by warpech** [comment]
To answer the above, most of the above points are done now. 

Further progress is tracked in https://github.com/Starcounter/Guidelines (issues and gitbook)

The part regarding the client package management is moved to https://github.com/Starcounter/RebelsLounge/issues/114
