### ISSUE TITLE
JSON Web Token example

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#32]
Currently, there are 2 apps to authenticate a user using a cookie-based session:
- SignIn
- GoogleSignIn

For REST usage of the apps, we need a more API-oriented way to authenticate.

Let's make an example using [JSON Web Token](http://jwt.io/)
RFC draft: http://tools.ietf.org/html/draft-ietf-oauth-json-web-token
15 min video: https://www.youtube.com/watch?v=eWUkxzyB1Rk
Alternative introduction: http://angular-tips.com/blog/2014/05/json-web-tokens-introduction/

As a proof of concept, there should be a test suite that:
1. requests a token from SignIn app in a REST call for user `admin`
2. provides the token to SignIn app to check if the user is authenticated and refresh the token
3. ~~provides the token to UserAdmin app to request details of a `admin` user~~

**Comment by miyconst** [comment]
Currently I have a test method which issues JWT by username and password.

SignIn app looks for auth cookie and auth header on load. If the auth header contains jwt, then it is being parsed and user got authenticated.

This has been tested through Postman app, no js test so far.

I don't like the idea of passing jwt to UserAdmin app. UserAdmin app should not even know about authentication applications and what approaches they use. UserAdmin app should call a method of SC, something like `Starcounter.Authentication.GetCurrentUser()`, if there is a user, then read his roles and decide what to do next.

Maybe I am trying to "implement" asp.net inside SC again, but I like the approach of authentication in asp.net. 

In asp.net we have build in classes for required methods, such as `GetCurrentUser`, `IsSignedIn`, `GetUserRoles`. Every website uses those methods to decide which actions user has access to.

There is a default auth provider which uses ms-sql db, and any other provider can be used instead of it.

Something similar may be implemented in SC, I have some idea, but this should be discussed via HO/Skype call.

For JWT encode/decode I use this repo:
https://github.com/johnsheehan/jwt

**Comment by warpech** [comment]
The work so far is commited in https://github.com/Polyjuice/SignIn/commit/e90900cdc02df6429c543cc3c267e5ad89609d21

On a Hangout, me and @miyconst decided to freeze the work until it is more clear about how getting the current user and his permissions can be achieved through mapping.

**Comment by warpech** [comment]
We talked about this with @dan31, and the conclusion is that the possibility of sharing *authorisation* between apps should be revised after the mapping is implemented.

As for *authentication*, let's continue to use current solution for the time being (cookie based auth with lookup in Simplified.Ring5.SystemUserSession table)

As for *JSON Web Token*, let's limit it's usage to a single app until a broader solution is available. So from the initial post, only points 1 & 2 are valid. This way the app does not need to be aware of any other apps issuing the JWT.

**Comment by miyconst** [comment]
@warpech how exactly it should look in SignIn App?

I would like to make SignIn app be able to run standalone before we add some more features.

**Comment by warpech** [comment]
Traces of JSON Web Token POC are in SignIn app. This issue can be considered done.
