### ISSUE TITLE
Layout editor: Save all button

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/Polyjuice#49]
Add save all button that will save all juicy tiles' layouts

**Comment by warpech** [comment]
I think that the regular button should act as "Save all" button. Otherwise it is hard for me to judge what layout I am saving.

I understand the argument that I might want to temporarily hide Partial A, then make layout changes in Partial B and save only B. But I can overcome this by restoring A before hitting save.

**Comment by miyconst** [comment]
Does this mean, that currently save button saves only selected element?

**Comment by warpech** [comment]
It saves the layout for `juicy-tile-grid` of the currently edited element.

I propose to have a single "Save" button that saves all `juicy-tile-grid` setups which are in dirty state. 

BUT, if there is more than one dirty `juicy-tile-grid` setup, the button will show a prompt for confirmation before saving each of them.

**Comment by warpech** [comment]
The same rule should apply to "Revert" button. It should revert all juicy-tile-grids that are in dirty state.

**Comment by miyconst** [comment]
This issue can be closed after https://github.com/Polyjuice/Launcher/issues/126 is done.

**Comment by warpech** [comment]
Closing this issue, because it was regarding the discontinued old layout editor.
