### ISSUE TITLE
Strange behavior when returning non-root JSON

### ISSUE THREAD

**Issue by alemoi** [Polyjuice/Polyjuice#56]
Running Launcher and People apps. In People application, e.g. on line Polyjuice\People\src\People\Api\MainHandlers.cs:55 returning `return master.CurrentPage;` instead of `return master;` then Launcher menu links Persons and Organizations are not "clickable". I guess its some problem with JSON patch messages there.

**Comment by alemoi** [comment]
@chrhol can you please check this? Thank you!

**Comment by chrhol** [comment]
I'm not sure exactly what goes wrong. I need to spend a little more time figuring out what the difference is when returning `master.CurrentPage` instead of `master`. At first glance I can't really see that it should be any different, but it obviously is since it does not work when `master.CurrentPage` is returned :)

**Comment by warpech** [comment]
This is of high importance. It worked ok 2 weeks ago (for example 2.0.3131.3). We can discuss this if there is some ambiguity about what is the desired behaviour. I can also investigate what is the version that broke it.

**Comment by chrhol** [comment]
I think it has something to do with stepsiblings not correctly being marked as dirty, but only the parent. That is why it works when returning the root (or master).

> It worked ok 2 weeks ago (for example 2.0.3131.3). 

Yes, there was a change in the responsehandling. In earlier versions we always traversed the json to the root and used that one. This was changed so we actually use the json that is returned, and then you get this bug.

> I can also investigate what is the version that broke it.

I think it was this commit that changed it, https://github.com/Starcounter/Starcounter/commit/5d876cc154ce954d70039387878729c1d403aa1a, on line 80 in AppRestServer.cs we previously always set the resource on the response to the root json.

> We can discuss this if there is some ambiguity about what is the desired behaviour.

That would be good I think. We should decide how we want it to work, because now we sometimes returns the root from some handlers and sometimes we return non-root.

**Comment by alemoi** [comment]
I suppose we should be able to return both root and non-root JSON responses. What do you think?

**Comment by chrhol** [comment]
> I suppose we should be able to return both root and non-root JSON responses. What do you think?

Yes I agree. I feel that I'm not entirely sure what to return from a handler though :) So it would be good to just have a clear answer on when you should return what from these "hybrid"-handlers.

**Comment by chrhol** [comment]
I've pushed a fix for this issue to develop. Lets discuss this in the office to make sure it works as we want.

**Comment by chrhol** [comment]
The current solution seems to be working and it is now possible to return non-root json which will work properly. Will close this issue.
