### ISSUE TITLE
Fix "partial.* for polyjuice-include is missing" warnings

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Polyjuice#63]
There is plenty of warnings in Launcher. 

@tomalec: What is the reason for them? Can you propose a solution?

![image](https://cloud.githubusercontent.com/assets/566463/8355650/a7ef8298-1b50-11e5-98b8-750a0c1887a0.png)

**Comment by tomalec** [comment]
The reason is that, the given partial does not have `.PartialId`, and `.Html` properties ;) The soulution would be to add ".Html" property to the main partial, at:
- [ ] https://github.com/Polyjuice/Launcher/blob/de655977fe93f4d69938baee0c5b968ab5efad21/src/Launcher/viewmodels/Launcher.json.cs#L26
- [ ] https://github.com/Polyjuice/Launcher/blob/f73c2dbb50787b1bbde8df4cb5488622d2df79f9/src/Launcher/api/LauncherHelper.cs#L96
- [ ] https://github.com/Polyjuice/Launcher/blob/f73c2dbb50787b1bbde8df4cb5488622d2df79f9/src/Launcher/api/LauncherHelper.cs#L109

**Comment by warpech** [comment]
Cool! @miyconst could you try that?

**Comment by miyconst** [comment]
Well, I managed to rid off the warnings, but this adds two more empty html files and requests.

`Launcher.searchBar.preview` is nested from `Starcounter.Page` and has its own empty html page (`SearchPreviewPage.html`). Same for `Launcher.results` with `ResultPage.html`.

@warpech, @tomalec, if this is okay, then close the issue, please.

**Comment by warpech** [comment]
These empty HTML files get merged to the responses from other apps, so they don't create additional requests, right?

Closing then, thanks!

**Comment by tomalec** [comment]
They do create additional (browser->server) request, if there is no other app response, we will ask for this empty html. Speaking of internal SC requests there will be no additional request as there were already `Self.GET`, but previously it returned nothing, and now it will always return path for empty HTML to be requested by `polyjuice-include`.

**Comment by warpech** [comment]
Acknowledged, thanks :)
